class TaskError(Exception):
    """
    A custom exception for failures related to a Celery task.
    """

    pass
